/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cat.proven.leisure.ui.filter;

/**
 *
 * @author jose
 */
public class FilterPanel extends javax.swing.JPanel {

    /**
     * Creates new form FilterPanel
     */
    public FilterPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filterAgePanel = new cat.proven.leisure.ui.filter.FilterAgePanel();
        filterActivityPanel = new cat.proven.leisure.ui.filter.FilterActivityPanel();

        setLayout(new java.awt.CardLayout());
        add(filterAgePanel, "card2");
        add(filterActivityPanel, "card3");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private cat.proven.leisure.ui.filter.FilterActivityPanel filterActivityPanel;
    private cat.proven.leisure.ui.filter.FilterAgePanel filterAgePanel;
    // End of variables declaration//GEN-END:variables
}
