
package cat.proven.leisure.main;

/**
 *
 * @author Jose
 */
public class AgeFilterPanel extends javax.swing.JPanel {

    /**
     * Creates new form AgeFilterPanel
     */
    public AgeFilterPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfLower = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfUpper = new javax.swing.JTextField();
        btFilter = new javax.swing.JButton();

        jLabel1.setText("Age between");
        add(jLabel1);

        tfLower.setText("jTextField1");
        add(tfLower);

        jLabel2.setText("and");
        add(jLabel2);

        tfUpper.setText("jTextField1");
        add(tfUpper);

        btFilter.setText("Filter");
        add(btFilter);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tfLower;
    private javax.swing.JTextField tfUpper;
    // End of variables declaration//GEN-END:variables
}
