/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cat.proven.leisure.ui.users;

/**
 *
 * @author jmorenp
 */
public class UsersFormPanel extends javax.swing.JPanel {

    /**
     * Creates new form UsersFormPanel
     */
    public UsersFormPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbHeader = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        btFirst = new javax.swing.JButton();
        btPrev = new javax.swing.JButton();
        btNext = new javax.swing.JButton();
        btLast = new javax.swing.JButton();
        btFirst4 = new javax.swing.JButton();
        dataPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfAge = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        lbHeader.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbHeader.setForeground(new java.awt.Color(0, 153, 153));
        lbHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHeader.setText("Users browser");
        add(lbHeader, java.awt.BorderLayout.PAGE_START);

        btFirst.setText("<<");
        btFirst.setPreferredSize(new java.awt.Dimension(50, 20));
        buttonPanel.add(btFirst);

        btPrev.setText("<");
        btPrev.setPreferredSize(new java.awt.Dimension(50, 20));
        buttonPanel.add(btPrev);

        btNext.setText(">");
        btNext.setPreferredSize(new java.awt.Dimension(50, 20));
        buttonPanel.add(btNext);

        btLast.setText(">>");
        btLast.setPreferredSize(new java.awt.Dimension(50, 20));
        buttonPanel.add(btLast);

        btFirst4.setText("<<");
        btFirst4.setPreferredSize(new java.awt.Dimension(50, 20));
        buttonPanel.add(btFirst4);

        add(buttonPanel, java.awt.BorderLayout.PAGE_END);

        dataPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Id");
        dataPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        tfId.setText("jTextField1");
        dataPanel.add(tfId, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 190, -1));

        jLabel2.setText("Name");
        dataPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        tfName.setText("jTextField1");
        dataPanel.add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 190, -1));

        tfAge.setText("jTextField1");
        dataPanel.add(tfAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 190, -1));

        jLabel3.setText("Age");
        dataPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        add(dataPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFirst;
    private javax.swing.JButton btFirst4;
    private javax.swing.JButton btLast;
    private javax.swing.JButton btNext;
    private javax.swing.JButton btPrev;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbHeader;
    private javax.swing.JTextField tfAge;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
