/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cat.proven.leisure.ui.users;

/**
 *
 * @author jmorenp
 */
public class UsersTablePanel extends javax.swing.JPanel {

    /**
     * Creates new form UsersTablePanel
     */
    public UsersTablePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbHeader = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        lbHeader.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbHeader.setForeground(new java.awt.Color(0, 102, 255));
        lbHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHeader.setText("List of users");
        add(lbHeader, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbHeader;
    // End of variables declaration//GEN-END:variables
}
