package cat.proven.leisure.main;

import cat.proven.leisure.model.User;
import java.util.List;

/**
 *
 * @author José
 */
public class FilterUsersPanel extends javax.swing.JPanel {

    /**
     * Creates new form FilterUsersPanel
     */
    public FilterUsersPanel() {
        initComponents();
        filterPanel.getActivityFilterPanel()
                .addPropertyChangeListener(
                        "users", 
                        (evt) -> {
                            List<User> users = (List<User>) evt.getNewValue();
                            usersFormPanel.setUsers(users);
                        });
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filterPanel = new cat.proven.leisure.main.FilterPanel();
        usersFormPanel = new cat.proven.leisure.main.UsersFormPanel();

        setLayout(new java.awt.BorderLayout());
        add(filterPanel, java.awt.BorderLayout.NORTH);
        add(usersFormPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public FilterPanel getFilterPanel() {
        return filterPanel;
    }

    public UsersFormPanel getUsersFormPanel() {
        return usersFormPanel;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private cat.proven.leisure.main.FilterPanel filterPanel;
    private cat.proven.leisure.main.UsersFormPanel usersFormPanel;
    // End of variables declaration//GEN-END:variables
    
}
