package cat.proven.leisure.main;

import cat.proven.leisure.model.User;
import java.util.List;

/**
 *
 * @author alumne
 */
public class UsersFormPanel extends javax.swing.JPanel {

    /**
     * Creates new form UsersFormPanel
     */
    public UsersFormPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        btFirst = new javax.swing.JButton();
        btPreviuos = new javax.swing.JButton();
        btNext = new javax.swing.JButton();
        btLast = new javax.swing.JButton();
        dataPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        tfAge = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        header.setBackground(new java.awt.Color(0, 102, 102));
        header.setForeground(new java.awt.Color(51, 51, 255));
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setText("User form");
        add(header, java.awt.BorderLayout.PAGE_START);

        btFirst.setText("<<");
        btFirst.setPreferredSize(new java.awt.Dimension(50, 25));
        btFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFirstActionPerformed(evt);
            }
        });
        buttonPanel.add(btFirst);

        btPreviuos.setText("<");
        btPreviuos.setPreferredSize(new java.awt.Dimension(50, 25));
        buttonPanel.add(btPreviuos);

        btNext.setText(">");
        btNext.setPreferredSize(new java.awt.Dimension(50, 25));
        buttonPanel.add(btNext);

        btLast.setText(">>");
        btLast.setPreferredSize(new java.awt.Dimension(50, 25));
        btLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLastActionPerformed(evt);
            }
        });
        buttonPanel.add(btLast);

        add(buttonPanel, java.awt.BorderLayout.SOUTH);

        jLabel1.setText("Id");

        jLabel2.setText("Name");

        jLabel3.setText("Age");

        tfId.setText("jTextField1");

        tfName.setText("jTextField2");

        tfAge.setText("jTextField3");

        javax.swing.GroupLayout dataPanelLayout = new javax.swing.GroupLayout(dataPanel);
        dataPanel.setLayout(dataPanelLayout);
        dataPanelLayout.setHorizontalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(48, 48, 48)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfId, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(tfName)
                    .addComponent(tfAge))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        dataPanelLayout.setVerticalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        add(dataPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFirstActionPerformed
        setSelectedUser(0);
    }//GEN-LAST:event_btFirstActionPerformed

    private void btLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLastActionPerformed
        setSelectedUser(users.size()-1);
    }//GEN-LAST:event_btLastActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFirst;
    private javax.swing.JButton btLast;
    private javax.swing.JButton btNext;
    private javax.swing.JButton btPreviuos;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JLabel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tfAge;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables

    private List<User> users;
    private int selectedUser;

    public static final String PROP_USERS = "users";

    /**
     * Get the value of users
     *
     * @return the value of users
     */
    public List<User> getUsers() {
        return users;
    }

    /**
     * Set the value of users
     *
     * @param users new value of users
     */
    public void setUsers(List<User> users) {
        List<User> oldUsers = this.users;
        this.users = users;
        this.selectedUser = 0;
        firePropertyChange(PROP_USERS, oldUsers, users);
        writeToForm();
        System.out.println("setUsers:"+users);
    }

    public int getSelectedUser() {
        return selectedUser;
    }

    public void setSelectedUser(int selectedUser) {
        this.selectedUser = selectedUser;
        writeToForm();
    }

    private void writeToForm() {
        User u = users.get(selectedUser);
        tfId.setText(String.valueOf(u.getId()));
        tfName.setText(u.getName());
        tfAge.setText(String.valueOf(u.getAge()));
    }
    
}
