package cat.proven.leisure.main;

import cat.proven.leisure.model.Activity;
import cat.proven.leisure.model.LeisureService;
import cat.proven.leisure.model.User;
import java.awt.Component;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author José Moreno
 */
public class ActivityFilterPanel extends javax.swing.JPanel {
    
    private LeisureService dataService;
    private List<User> users;
    
    /**
     * Creates new form ActivityFilterPanel
     */
    public ActivityFilterPanel() {
        dataService = new LeisureService();
        initComponents();
        cbActivity.setSelectedIndex(0);
        cbActivity.setRenderer(new ActivityComboBoxRenderer());
    }
    
    /**
     * Get the value of users
     *
     * @return the value of users
     */
    public List<User> getUsers() {
        return users;
    }

    /**
     * Set the value of users
     *
     * @param users new value of users
     */
    public void setUsers(List<User> users) {
        List<User> oldValue = this.users;
        this.users = users;
        System.out.println("ActivityFilterPanel::setUsers"+users);
        firePropertyChange("users", null, users);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbActivity = new javax.swing.JLabel();
        cbActivity = new javax.swing.JComboBox<>();

        lbActivity.setText("Activity");
        add(lbActivity);

        cbActivity.setModel(getComboBoxModel());
        cbActivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActivityActionPerformed(evt);
            }
        });
        add(cbActivity);
    }// </editor-fold>//GEN-END:initComponents

    private void cbActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActivityActionPerformed
        if (cbActivity == evt.getSource()) {
            Activity selectedItem = (Activity) cbActivity.getSelectedItem();
            List<User> users = dataService.getUsersByActivity(selectedItem);
            setUsers(users);
        }
    }//GEN-LAST:event_cbActivityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Activity> cbActivity;
    private javax.swing.JLabel lbActivity;
    // End of variables declaration//GEN-END:variables

    public ComboBoxModel getComboBoxModel() {
        //LeisureService dataService = new LeisureService();
        List<Activity> actList = dataService.getAllActivities();
        return new DefaultComboBoxModel(
                actList.toArray(Activity[]::new)
        );
    }
    
 class ActivityComboBoxRenderer extends JLabel implements ListCellRenderer<Activity> {

        @Override
        public Component getListCellRendererComponent(
                JList<? extends Activity> list, Activity value, int index,
                boolean isSelected, boolean cellHasFocus) {
            if (isSelected) {
                setBackground(list.getSelectionBackground());
                setForeground(list.getSelectionForeground());
            } else {
                setBackground(list.getBackground());
                setForeground(list.getForeground());
            }
            setText(value.getName());
            return this;
        }

    }    
    
    
}
