package cat.proven.leisure.main;

import cat.proven.leisure.model.LeisureService;
import cat.proven.leisure.model.User;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author alumne
 */
public class AgeFilterPanel extends javax.swing.JPanel {

    /**
     * Creates new form AgeFilterPanel
     */
    public AgeFilterPanel() {
        dataService = new LeisureService();
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfLower = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfUpper = new javax.swing.JTextField();
        btFilter = new javax.swing.JButton();

        jLabel1.setText("Age between");
        add(jLabel1);

        tfLower.setText("jTextField1");
        add(tfLower);

        jLabel2.setText("and");
        add(jLabel2);

        tfUpper.setText("jTextField1");
        add(tfUpper);

        btFilter.setText("Filter");
        btFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFilterActionPerformed(evt);
            }
        });
        add(btFilter);
    }// </editor-fold>//GEN-END:initComponents

    private void btFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFilterActionPerformed

        try {
            lower = Integer.parseInt(tfLower.getText());
            upper = Integer.parseInt(tfUpper.getText());
            List<User> result = 
                    dataService.getUsersByAgeLimits(lower, upper);
            setUsers(result);            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    this, 
                    "Only digits, please!", 
                    "Validation error", 
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btFilterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tfLower;
    private javax.swing.JTextField tfUpper;
    // End of variables declaration//GEN-END:variables
    private LeisureService dataService;

    private List<User> users;

    public static final String PROP_USERS = "users";

    /**
     * Get the value of users
     *
     * @return the value of users
     */
    public List<User> getUsers() {
        return users;
    }

    /**
     * Set the value of users
     *
     * @param users new value of users
     */
    public void setUsers(List<User> users) {
        List<User> oldUsers = this.users;
        this.users = users;
        firePropertyChange(PROP_USERS, oldUsers, users);
    }

    private int lower;
    private int upper;
}
